//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.ServiceNS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DCUser", Namespace="http://schemas.datacontract.org/2004/07/WCFDotNet.DataContracts")]
    [System.SerializableAttribute()]
    public partial class DCUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool OnlineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DAL.ServiceNS.DCPost PostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DAL.ServiceNS.DCProvider ProviderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Online {
            get {
                return this.OnlineField;
            }
            set {
                if ((this.OnlineField.Equals(value) != true)) {
                    this.OnlineField = value;
                    this.RaisePropertyChanged("Online");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DAL.ServiceNS.DCPost Post {
            get {
                return this.PostField;
            }
            set {
                if ((object.ReferenceEquals(this.PostField, value) != true)) {
                    this.PostField = value;
                    this.RaisePropertyChanged("Post");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DAL.ServiceNS.DCProvider Provider {
            get {
                return this.ProviderField;
            }
            set {
                if ((object.ReferenceEquals(this.ProviderField, value) != true)) {
                    this.ProviderField = value;
                    this.RaisePropertyChanged("Provider");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DCPost", Namespace="http://schemas.datacontract.org/2004/07/WCFDotNet.DataContracts")]
    [System.SerializableAttribute()]
    public partial class DCPost : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> SalaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DAL.ServiceNS.DCUser[] UsersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Salary {
            get {
                return this.SalaryField;
            }
            set {
                if ((this.SalaryField.Equals(value) != true)) {
                    this.SalaryField = value;
                    this.RaisePropertyChanged("Salary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DAL.ServiceNS.DCUser[] Users {
            get {
                return this.UsersField;
            }
            set {
                if ((object.ReferenceEquals(this.UsersField, value) != true)) {
                    this.UsersField = value;
                    this.RaisePropertyChanged("Users");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DCProvider", Namespace="http://schemas.datacontract.org/2004/07/WCFDotNet.DataContracts")]
    [System.SerializableAttribute()]
    public partial class DCProvider : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DAL.ServiceNS.DCItemFromProvider[] ItemFromProvidersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DAL.ServiceNS.DCUser UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DAL.ServiceNS.DCItemFromProvider[] ItemFromProviders {
            get {
                return this.ItemFromProvidersField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemFromProvidersField, value) != true)) {
                    this.ItemFromProvidersField = value;
                    this.RaisePropertyChanged("ItemFromProviders");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DAL.ServiceNS.DCUser User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DCItemFromProvider", Namespace="http://schemas.datacontract.org/2004/07/WCFDotNet.DataContracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DAL.ServiceNS.DCCpuFromProvider))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DAL.ServiceNS.DCMBFromProvider))]
    public partial class DCItemFromProvider : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal BuyPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DAL.ServiceNS.DCProducer ProducerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DAL.ServiceNS.DCProvider ProviderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BuyPrice {
            get {
                return this.BuyPriceField;
            }
            set {
                if ((this.BuyPriceField.Equals(value) != true)) {
                    this.BuyPriceField = value;
                    this.RaisePropertyChanged("BuyPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DAL.ServiceNS.DCProducer Producer {
            get {
                return this.ProducerField;
            }
            set {
                if ((object.ReferenceEquals(this.ProducerField, value) != true)) {
                    this.ProducerField = value;
                    this.RaisePropertyChanged("Producer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DAL.ServiceNS.DCProvider Provider {
            get {
                return this.ProviderField;
            }
            set {
                if ((object.ReferenceEquals(this.ProviderField, value) != true)) {
                    this.ProviderField = value;
                    this.RaisePropertyChanged("Provider");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DCProducer", Namespace="http://schemas.datacontract.org/2004/07/WCFDotNet.DataContracts")]
    [System.SerializableAttribute()]
    public partial class DCProducer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DCCpuFromProvider", Namespace="http://schemas.datacontract.org/2004/07/WCFDotNet.DataContracts")]
    [System.SerializableAttribute()]
    public partial class DCCpuFromProvider : DAL.ServiceNS.DCItemFromProvider {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CpuSocketField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FrequencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ThreadsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VideoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cash {
            get {
                return this.CashField;
            }
            set {
                if ((object.ReferenceEquals(this.CashField, value) != true)) {
                    this.CashField = value;
                    this.RaisePropertyChanged("Cash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Core {
            get {
                return this.CoreField;
            }
            set {
                if ((this.CoreField.Equals(value) != true)) {
                    this.CoreField = value;
                    this.RaisePropertyChanged("Core");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CpuSocket {
            get {
                return this.CpuSocketField;
            }
            set {
                if ((object.ReferenceEquals(this.CpuSocketField, value) != true)) {
                    this.CpuSocketField = value;
                    this.RaisePropertyChanged("CpuSocket");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Frequency {
            get {
                return this.FrequencyField;
            }
            set {
                if ((this.FrequencyField.Equals(value) != true)) {
                    this.FrequencyField = value;
                    this.RaisePropertyChanged("Frequency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Threads {
            get {
                return this.ThreadsField;
            }
            set {
                if ((this.ThreadsField.Equals(value) != true)) {
                    this.ThreadsField = value;
                    this.RaisePropertyChanged("Threads");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Video {
            get {
                return this.VideoField;
            }
            set {
                if ((object.ReferenceEquals(this.VideoField, value) != true)) {
                    this.VideoField = value;
                    this.RaisePropertyChanged("Video");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DCMBFromProvider", Namespace="http://schemas.datacontract.org/2004/07/WCFDotNet.DataContracts")]
    [System.SerializableAttribute()]
    public partial class DCMBFromProvider : DAL.ServiceNS.DCItemFromProvider {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChipSetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MBSocketField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PciEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RAMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USBField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChipSet {
            get {
                return this.ChipSetField;
            }
            set {
                if ((object.ReferenceEquals(this.ChipSetField, value) != true)) {
                    this.ChipSetField = value;
                    this.RaisePropertyChanged("ChipSet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MBSocket {
            get {
                return this.MBSocketField;
            }
            set {
                if ((object.ReferenceEquals(this.MBSocketField, value) != true)) {
                    this.MBSocketField = value;
                    this.RaisePropertyChanged("MBSocket");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PciE {
            get {
                return this.PciEField;
            }
            set {
                if ((object.ReferenceEquals(this.PciEField, value) != true)) {
                    this.PciEField = value;
                    this.RaisePropertyChanged("PciE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RAM {
            get {
                return this.RAMField;
            }
            set {
                if ((object.ReferenceEquals(this.RAMField, value) != true)) {
                    this.RAMField = value;
                    this.RaisePropertyChanged("RAM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USB {
            get {
                return this.USBField;
            }
            set {
                if ((object.ReferenceEquals(this.USBField, value) != true)) {
                    this.USBField = value;
                    this.RaisePropertyChanged("USB");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DCItemFromShop", Namespace="http://schemas.datacontract.org/2004/07/WCFDotNet.DataContracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DAL.ServiceNS.DCMBFromShop))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DAL.ServiceNS.DCCpuFromShop))]
    public partial class DCItemFromShop : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DAL.ServiceNS.DCProducer ProducerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SalaryPriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DAL.ServiceNS.DCProducer Producer {
            get {
                return this.ProducerField;
            }
            set {
                if ((object.ReferenceEquals(this.ProducerField, value) != true)) {
                    this.ProducerField = value;
                    this.RaisePropertyChanged("Producer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SalaryPrice {
            get {
                return this.SalaryPriceField;
            }
            set {
                if ((this.SalaryPriceField.Equals(value) != true)) {
                    this.SalaryPriceField = value;
                    this.RaisePropertyChanged("SalaryPrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DCMBFromShop", Namespace="http://schemas.datacontract.org/2004/07/WCFDotNet.DataContracts")]
    [System.SerializableAttribute()]
    public partial class DCMBFromShop : DAL.ServiceNS.DCItemFromShop {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChipSetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MBSocketField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PciEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RAMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USBField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChipSet {
            get {
                return this.ChipSetField;
            }
            set {
                if ((object.ReferenceEquals(this.ChipSetField, value) != true)) {
                    this.ChipSetField = value;
                    this.RaisePropertyChanged("ChipSet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MBSocket {
            get {
                return this.MBSocketField;
            }
            set {
                if ((object.ReferenceEquals(this.MBSocketField, value) != true)) {
                    this.MBSocketField = value;
                    this.RaisePropertyChanged("MBSocket");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PciE {
            get {
                return this.PciEField;
            }
            set {
                if ((object.ReferenceEquals(this.PciEField, value) != true)) {
                    this.PciEField = value;
                    this.RaisePropertyChanged("PciE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RAM {
            get {
                return this.RAMField;
            }
            set {
                if ((object.ReferenceEquals(this.RAMField, value) != true)) {
                    this.RAMField = value;
                    this.RaisePropertyChanged("RAM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USB {
            get {
                return this.USBField;
            }
            set {
                if ((object.ReferenceEquals(this.USBField, value) != true)) {
                    this.USBField = value;
                    this.RaisePropertyChanged("USB");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DCCpuFromShop", Namespace="http://schemas.datacontract.org/2004/07/WCFDotNet.DataContracts")]
    [System.SerializableAttribute()]
    public partial class DCCpuFromShop : DAL.ServiceNS.DCItemFromShop {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CpuSocketField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FrequencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ThreadsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VideoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cash {
            get {
                return this.CashField;
            }
            set {
                if ((object.ReferenceEquals(this.CashField, value) != true)) {
                    this.CashField = value;
                    this.RaisePropertyChanged("Cash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Core {
            get {
                return this.CoreField;
            }
            set {
                if ((this.CoreField.Equals(value) != true)) {
                    this.CoreField = value;
                    this.RaisePropertyChanged("Core");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CpuSocket {
            get {
                return this.CpuSocketField;
            }
            set {
                if ((object.ReferenceEquals(this.CpuSocketField, value) != true)) {
                    this.CpuSocketField = value;
                    this.RaisePropertyChanged("CpuSocket");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Frequency {
            get {
                return this.FrequencyField;
            }
            set {
                if ((this.FrequencyField.Equals(value) != true)) {
                    this.FrequencyField = value;
                    this.RaisePropertyChanged("Frequency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Threads {
            get {
                return this.ThreadsField;
            }
            set {
                if ((this.ThreadsField.Equals(value) != true)) {
                    this.ThreadsField = value;
                    this.RaisePropertyChanged("Threads");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Video {
            get {
                return this.VideoField;
            }
            set {
                if ((object.ReferenceEquals(this.VideoField, value) != true)) {
                    this.VideoField = value;
                    this.RaisePropertyChanged("Video");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DCSaleItem", Namespace="http://schemas.datacontract.org/2004/07/WCFDotNet.DataContracts")]
    [System.SerializableAttribute()]
    public partial class DCSaleItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DAL.ServiceNS.DCItemFromShop ItemFromShopField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SaleTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DAL.ServiceNS.DCItemFromShop ItemFromShop {
            get {
                return this.ItemFromShopField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemFromShopField, value) != true)) {
                    this.ItemFromShopField = value;
                    this.RaisePropertyChanged("ItemFromShop");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SaleTime {
            get {
                return this.SaleTimeField;
            }
            set {
                if ((this.SaleTimeField.Equals(value) != true)) {
                    this.SaleTimeField = value;
                    this.RaisePropertyChanged("SaleTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DCBuyItem", Namespace="http://schemas.datacontract.org/2004/07/WCFDotNet.DataContracts")]
    [System.SerializableAttribute()]
    public partial class DCBuyItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DAL.ServiceNS.DCItemFromProvider ItemFromProviderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeBuyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DAL.ServiceNS.DCItemFromProvider ItemFromProvider {
            get {
                return this.ItemFromProviderField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemFromProviderField, value) != true)) {
                    this.ItemFromProviderField = value;
                    this.RaisePropertyChanged("ItemFromProvider");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimeBuy {
            get {
                return this.TimeBuyField;
            }
            set {
                if ((this.TimeBuyField.Equals(value) != true)) {
                    this.TimeBuyField = value;
                    this.RaisePropertyChanged("TimeBuy");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceNS.IShopServer")]
    public interface IShopServer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShopServer/GetUser", ReplyAction="http://tempuri.org/IShopServer/GetUserResponse")]
        DAL.ServiceNS.DCUser GetUser(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShopServer/GetDCItemFromShop", ReplyAction="http://tempuri.org/IShopServer/GetDCItemFromShopResponse")]
        DAL.ServiceNS.DCItemFromShop[] GetDCItemFromShop();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShopServer/UserOff", ReplyAction="http://tempuri.org/IShopServer/UserOffResponse")]
        void UserOff(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShopServer/UserOn", ReplyAction="http://tempuri.org/IShopServer/UserOnResponse")]
        void UserOn(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShopServer/SaleItems", ReplyAction="http://tempuri.org/IShopServer/SaleItemsResponse")]
        void SaleItems(DAL.ServiceNS.DCSaleItem[] DCSaleItems);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShopServer/GetItemsFromProvider", ReplyAction="http://tempuri.org/IShopServer/GetItemsFromProviderResponse")]
        DAL.ServiceNS.DCItemFromProvider[] GetItemsFromProvider();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShopServer/BuyItems", ReplyAction="http://tempuri.org/IShopServer/BuyItemsResponse")]
        void BuyItems([System.ServiceModel.MessageParameterAttribute(Name="BuyItems")] DAL.ServiceNS.DCBuyItem[] BuyItems1);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IShopServerChannel : DAL.ServiceNS.IShopServer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ShopServerClient : System.ServiceModel.ClientBase<DAL.ServiceNS.IShopServer>, DAL.ServiceNS.IShopServer {
        
        public ShopServerClient() {
        }
        
        public ShopServerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ShopServerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShopServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShopServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DAL.ServiceNS.DCUser GetUser(string login, string password) {
            return base.Channel.GetUser(login, password);
        }
        
        public DAL.ServiceNS.DCItemFromShop[] GetDCItemFromShop() {
            return base.Channel.GetDCItemFromShop();
        }
        
        public void UserOff(int Id) {
            base.Channel.UserOff(Id);
        }
        
        public void UserOn(int Id) {
            base.Channel.UserOn(Id);
        }
        
        public void SaleItems(DAL.ServiceNS.DCSaleItem[] DCSaleItems) {
            base.Channel.SaleItems(DCSaleItems);
        }
        
        public DAL.ServiceNS.DCItemFromProvider[] GetItemsFromProvider() {
            return base.Channel.GetItemsFromProvider();
        }
        
        public void BuyItems(DAL.ServiceNS.DCBuyItem[] BuyItems1) {
            base.Channel.BuyItems(BuyItems1);
        }
    }
}
